trigger:
  - frontend

resources:
  - repo: self

variables:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and Push Image Stage
    jobs:
      - job: Build
        displayName: Build and Push Image To Docker Hub
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Docker@2
            displayName: Build and Push
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'leonardomm26/frontend'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                latest
                $(Build.BuildId)
          
